ERROR - 2024-05-26 11:38:11 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CV_CI4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\CV_CI4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CV_CI4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\CV_CI4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CV_CI4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\CV_CI4\app\Controllers\CvController.php(12): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\CV_CI4\system\CodeIgniter.php(933): App\Controllers\CvController->index()
#8 C:\xampp\htdocs\CV_CI4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CvController))
#9 C:\xampp\htdocs\CV_CI4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\CV_CI4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\CV_CI4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\CV_CI4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\xampp\htdocs\CV_CI4\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CV_CI4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CV_CI4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\CV_CI4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\CV_CI4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\CV_CI4\app\Controllers\CvController.php(12): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\CV_CI4\system\CodeIgniter.php(933): App\Controllers\CvController->index()
#7 C:\xampp\htdocs\CV_CI4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CvController))
#8 C:\xampp\htdocs\CV_CI4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\CV_CI4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\CV_CI4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\CV_CI4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 C:\xampp\htdocs\CV_CI4\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-05-26 11:38:11 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `cv`', [], false)
 3 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\CvController.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\CvController->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CvController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp\\htdocs\\CV_CI4\\public\\index.php')
ERROR - 2024-05-26 11:41:58 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CV_CI4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\CV_CI4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(1471): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#4 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(1490): CodeIgniter\Database\BaseConnection->listTables()
#5 C:\xampp\htdocs\CV_CI4\system\Database\MigrationRunner.php(759): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#6 C:\xampp\htdocs\CV_CI4\system\Database\MigrationRunner.php(163): CodeIgniter\Database\MigrationRunner->ensureTable()
#7 C:\xampp\htdocs\CV_CI4\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\CV_CI4\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\CV_CI4\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\CV_CI4\system\Boot.php(338): CodeIgniter\CLI\Console->run()
#11 C:\xampp\htdocs\CV_CI4\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 C:\xampp\htdocs\CV_CI4\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\CV_CI4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(1471): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#3 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(1490): CodeIgniter\Database\BaseConnection->listTables()
#4 C:\xampp\htdocs\CV_CI4\system\Database\MigrationRunner.php(759): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#5 C:\xampp\htdocs\CV_CI4\system\Database\MigrationRunner.php(163): CodeIgniter\Database\MigrationRunner->ensureTable()
#6 C:\xampp\htdocs\CV_CI4\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#7 C:\xampp\htdocs\CV_CI4\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Migrate->run(Array)
#8 C:\xampp\htdocs\CV_CI4\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('migrate', Array)
#9 C:\xampp\htdocs\CV_CI4\system\Boot.php(338): CodeIgniter\CLI\Console->run()
#10 C:\xampp\htdocs\CV_CI4\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#11 C:\xampp\htdocs\CV_CI4\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#12 {main}
ERROR - 2024-05-26 12:10:18 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\CV_CI4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\CV_CI4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'cv', 3306, '', 0)
#1 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CV_CI4\system\Database\Database.php(68): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CV_CI4\system\Database\Config.php(111): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#4 C:\xampp\htdocs\CV_CI4\system\Database\Seeder.php(98): CodeIgniter\Database\Config::forge(NULL)
#5 C:\xampp\htdocs\CV_CI4\system\Commands\Database\Seed.php(71): CodeIgniter\Database\Seeder->__construct(Object(Config\Database))
#6 C:\xampp\htdocs\CV_CI4\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Seed->run(Array)
#7 C:\xampp\htdocs\CV_CI4\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:seed', Array)
#8 C:\xampp\htdocs\CV_CI4\system\Boot.php(338): CodeIgniter\CLI\Console->run()
#9 C:\xampp\htdocs\CV_CI4\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#10 C:\xampp\htdocs\CV_CI4\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\CV_CI4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CV_CI4\system\Database\Database.php(68): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CV_CI4\system\Database\Config.php(111): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#3 C:\xampp\htdocs\CV_CI4\system\Database\Seeder.php(98): CodeIgniter\Database\Config::forge(NULL)
#4 C:\xampp\htdocs\CV_CI4\system\Commands\Database\Seed.php(71): CodeIgniter\Database\Seeder->__construct(Object(Config\Database))
#5 C:\xampp\htdocs\CV_CI4\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Seed->run(Array)
#6 C:\xampp\htdocs\CV_CI4\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:seed', Array)
#7 C:\xampp\htdocs\CV_CI4\system\Boot.php(338): CodeIgniter\CLI\Console->run()
#8 C:\xampp\htdocs\CV_CI4\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#9 C:\xampp\htdocs\CV_CI4\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#10 {main}
CRITICAL - 2024-05-26 12:10:18 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: CLI, Route: db:seed/CvSeeder]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\Database.php(68): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\Config.php(111): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
 3 SYSTEMPATH\Database\Seeder.php(98): CodeIgniter\Database\Config::forge(null)
 4 SYSTEMPATH\Commands\Database\Seed.php(71): CodeIgniter\Database\Seeder->__construct(Object(Config\Database))
 5 SYSTEMPATH\CLI\Commands.php(70): CodeIgniter\Commands\Database\Seed->run([...])
 6 SYSTEMPATH\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:seed', [...])
 7 SYSTEMPATH\Boot.php(338): CodeIgniter\CLI\Console->run()
 8 SYSTEMPATH\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
 9 ROOTPATH\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
ERROR - 2024-05-26 12:12:31 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'cv' in C:\xampp\htdocs\CV_CI4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\CV_CI4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'cv', 3306, '', 0)
#1 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CV_CI4\system\Database\Database.php(68): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CV_CI4\system\Database\Config.php(111): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#4 C:\xampp\htdocs\CV_CI4\system\Database\Seeder.php(98): CodeIgniter\Database\Config::forge(NULL)
#5 C:\xampp\htdocs\CV_CI4\system\Commands\Database\Seed.php(71): CodeIgniter\Database\Seeder->__construct(Object(Config\Database))
#6 C:\xampp\htdocs\CV_CI4\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Seed->run(Array)
#7 C:\xampp\htdocs\CV_CI4\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:seed', Array)
#8 C:\xampp\htdocs\CV_CI4\system\Boot.php(338): CodeIgniter\CLI\Console->run()
#9 C:\xampp\htdocs\CV_CI4\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#10 C:\xampp\htdocs\CV_CI4\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'cv' in C:\xampp\htdocs\CV_CI4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CV_CI4\system\Database\Database.php(68): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CV_CI4\system\Database\Config.php(111): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#3 C:\xampp\htdocs\CV_CI4\system\Database\Seeder.php(98): CodeIgniter\Database\Config::forge(NULL)
#4 C:\xampp\htdocs\CV_CI4\system\Commands\Database\Seed.php(71): CodeIgniter\Database\Seeder->__construct(Object(Config\Database))
#5 C:\xampp\htdocs\CV_CI4\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Seed->run(Array)
#6 C:\xampp\htdocs\CV_CI4\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:seed', Array)
#7 C:\xampp\htdocs\CV_CI4\system\Boot.php(338): CodeIgniter\CLI\Console->run()
#8 C:\xampp\htdocs\CV_CI4\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#9 C:\xampp\htdocs\CV_CI4\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#10 {main}
CRITICAL - 2024-05-26 12:12:31 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'cv'
[Method: CLI, Route: db:seed/CvSeeder]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\Database.php(68): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\Config.php(111): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
 3 SYSTEMPATH\Database\Seeder.php(98): CodeIgniter\Database\Config::forge(null)
 4 SYSTEMPATH\Commands\Database\Seed.php(71): CodeIgniter\Database\Seeder->__construct(Object(Config\Database))
 5 SYSTEMPATH\CLI\Commands.php(70): CodeIgniter\Commands\Database\Seed->run([...])
 6 SYSTEMPATH\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:seed', [...])
 7 SYSTEMPATH\Boot.php(338): CodeIgniter\CLI\Console->run()
 8 SYSTEMPATH\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
 9 ROOTPATH\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
ERROR - 2024-05-26 12:12:59 --> mysqli_sql_exception: No database selected in C:\xampp\htdocs\CV_CI4\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp\htdocs\CV_CI4\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `cv...', 0)
#1 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cv...')
#2 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cv...')
#3 C:\xampp\htdocs\CV_CI4\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cv...', Array, false)
#4 C:\xampp\htdocs\CV_CI4\app\Database\Seeds\CvSeeder.php(21): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\CV_CI4\system\Database\Seeder.php(147): App\Database\Seeds\CvSeeder->run()
#6 C:\xampp\htdocs\CV_CI4\system\Commands\Database\Seed.php(79): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#7 C:\xampp\htdocs\CV_CI4\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Seed->run(Array)
#8 C:\xampp\htdocs\CV_CI4\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:seed', Array)
#9 C:\xampp\htdocs\CV_CI4\system\Boot.php(338): CodeIgniter\CLI\Console->run()
#10 C:\xampp\htdocs\CV_CI4\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#11 C:\xampp\htdocs\CV_CI4\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#12 {main}
ERROR - 2024-05-26 12:14:57 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\CV_CI4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\CV_CI4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CV_CI4\system\Database\Database.php(68): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CV_CI4\system\Database\Config.php(111): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#4 C:\xampp\htdocs\CV_CI4\system\Database\Seeder.php(98): CodeIgniter\Database\Config::forge(NULL)
#5 C:\xampp\htdocs\CV_CI4\system\Commands\Database\Seed.php(71): CodeIgniter\Database\Seeder->__construct(Object(Config\Database))
#6 C:\xampp\htdocs\CV_CI4\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Seed->run(Array)
#7 C:\xampp\htdocs\CV_CI4\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:seed', Array)
#8 C:\xampp\htdocs\CV_CI4\system\Boot.php(338): CodeIgniter\CLI\Console->run()
#9 C:\xampp\htdocs\CV_CI4\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#10 C:\xampp\htdocs\CV_CI4\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\CV_CI4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CV_CI4\system\Database\Database.php(68): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CV_CI4\system\Database\Config.php(111): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#3 C:\xampp\htdocs\CV_CI4\system\Database\Seeder.php(98): CodeIgniter\Database\Config::forge(NULL)
#4 C:\xampp\htdocs\CV_CI4\system\Commands\Database\Seed.php(71): CodeIgniter\Database\Seeder->__construct(Object(Config\Database))
#5 C:\xampp\htdocs\CV_CI4\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Seed->run(Array)
#6 C:\xampp\htdocs\CV_CI4\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:seed', Array)
#7 C:\xampp\htdocs\CV_CI4\system\Boot.php(338): CodeIgniter\CLI\Console->run()
#8 C:\xampp\htdocs\CV_CI4\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#9 C:\xampp\htdocs\CV_CI4\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#10 {main}
CRITICAL - 2024-05-26 12:14:57 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: CLI, Route: db:seed/CvSeeder]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\Database.php(68): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\Config.php(111): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
 3 SYSTEMPATH\Database\Seeder.php(98): CodeIgniter\Database\Config::forge(null)
 4 SYSTEMPATH\Commands\Database\Seed.php(71): CodeIgniter\Database\Seeder->__construct(Object(Config\Database))
 5 SYSTEMPATH\CLI\Commands.php(70): CodeIgniter\Commands\Database\Seed->run([...])
 6 SYSTEMPATH\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:seed', [...])
 7 SYSTEMPATH\Boot.php(338): CodeIgniter\CLI\Console->run()
 8 SYSTEMPATH\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
 9 ROOTPATH\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
ERROR - 2024-05-26 12:15:40 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\CV_CI4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\CV_CI4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CV_CI4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\CV_CI4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CV_CI4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\CV_CI4\app\Controllers\CvController.php(12): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\CV_CI4\system\CodeIgniter.php(933): App\Controllers\CvController->index()
#8 C:\xampp\htdocs\CV_CI4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CvController))
#9 C:\xampp\htdocs\CV_CI4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\CV_CI4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\CV_CI4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\CV_CI4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\xampp\htdocs\CV_CI4\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\CV_CI4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CV_CI4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\CV_CI4\system\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\CV_CI4\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\CV_CI4\app\Controllers\CvController.php(12): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\CV_CI4\system\CodeIgniter.php(933): App\Controllers\CvController->index()
#7 C:\xampp\htdocs\CV_CI4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CvController))
#8 C:\xampp\htdocs\CV_CI4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\CV_CI4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\CV_CI4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\CV_CI4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 C:\xampp\htdocs\CV_CI4\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-05-26 12:15:40 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: cv]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `cv`', [], false)
 3 SYSTEMPATH\Model.php(275): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\CvController.php(12): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\CvController->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CvController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp\\htdocs\\CV_CI4\\public\\index.php')
ERROR - 2024-05-26 12:16:48 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\CV_CI4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\CV_CI4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CV_CI4\system\Database\Database.php(68): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CV_CI4\system\Database\Config.php(111): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#4 C:\xampp\htdocs\CV_CI4\system\Database\Seeder.php(98): CodeIgniter\Database\Config::forge(NULL)
#5 C:\xampp\htdocs\CV_CI4\system\Commands\Database\Seed.php(71): CodeIgniter\Database\Seeder->__construct(Object(Config\Database))
#6 C:\xampp\htdocs\CV_CI4\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Seed->run(Array)
#7 C:\xampp\htdocs\CV_CI4\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:seed', Array)
#8 C:\xampp\htdocs\CV_CI4\system\Boot.php(338): CodeIgniter\CLI\Console->run()
#9 C:\xampp\htdocs\CV_CI4\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#10 C:\xampp\htdocs\CV_CI4\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\CV_CI4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CV_CI4\system\Database\Database.php(68): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CV_CI4\system\Database\Config.php(111): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#3 C:\xampp\htdocs\CV_CI4\system\Database\Seeder.php(98): CodeIgniter\Database\Config::forge(NULL)
#4 C:\xampp\htdocs\CV_CI4\system\Commands\Database\Seed.php(71): CodeIgniter\Database\Seeder->__construct(Object(Config\Database))
#5 C:\xampp\htdocs\CV_CI4\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Seed->run(Array)
#6 C:\xampp\htdocs\CV_CI4\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:seed', Array)
#7 C:\xampp\htdocs\CV_CI4\system\Boot.php(338): CodeIgniter\CLI\Console->run()
#8 C:\xampp\htdocs\CV_CI4\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#9 C:\xampp\htdocs\CV_CI4\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#10 {main}
CRITICAL - 2024-05-26 12:16:48 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: CLI, Route: db:seed/CvSeeder]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\Database.php(68): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\Config.php(111): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
 3 SYSTEMPATH\Database\Seeder.php(98): CodeIgniter\Database\Config::forge(null)
 4 SYSTEMPATH\Commands\Database\Seed.php(71): CodeIgniter\Database\Seeder->__construct(Object(Config\Database))
 5 SYSTEMPATH\CLI\Commands.php(70): CodeIgniter\Commands\Database\Seed->run([...])
 6 SYSTEMPATH\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:seed', [...])
 7 SYSTEMPATH\Boot.php(338): CodeIgniter\CLI\Console->run()
 8 SYSTEMPATH\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
 9 ROOTPATH\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
ERROR - 2024-05-26 12:22:19 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'cv' in C:\xampp\htdocs\CV_CI4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\CV_CI4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'cv', 3306, '', 0)
#1 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CV_CI4\system\Database\Database.php(68): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CV_CI4\system\Database\Config.php(111): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#4 C:\xampp\htdocs\CV_CI4\system\Database\Seeder.php(98): CodeIgniter\Database\Config::forge(NULL)
#5 C:\xampp\htdocs\CV_CI4\system\Commands\Database\Seed.php(71): CodeIgniter\Database\Seeder->__construct(Object(Config\Database))
#6 C:\xampp\htdocs\CV_CI4\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Seed->run(Array)
#7 C:\xampp\htdocs\CV_CI4\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:seed', Array)
#8 C:\xampp\htdocs\CV_CI4\system\Boot.php(338): CodeIgniter\CLI\Console->run()
#9 C:\xampp\htdocs\CV_CI4\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#10 C:\xampp\htdocs\CV_CI4\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'cv' in C:\xampp\htdocs\CV_CI4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CV_CI4\system\Database\Database.php(68): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CV_CI4\system\Database\Config.php(111): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#3 C:\xampp\htdocs\CV_CI4\system\Database\Seeder.php(98): CodeIgniter\Database\Config::forge(NULL)
#4 C:\xampp\htdocs\CV_CI4\system\Commands\Database\Seed.php(71): CodeIgniter\Database\Seeder->__construct(Object(Config\Database))
#5 C:\xampp\htdocs\CV_CI4\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Seed->run(Array)
#6 C:\xampp\htdocs\CV_CI4\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:seed', Array)
#7 C:\xampp\htdocs\CV_CI4\system\Boot.php(338): CodeIgniter\CLI\Console->run()
#8 C:\xampp\htdocs\CV_CI4\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#9 C:\xampp\htdocs\CV_CI4\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#10 {main}
CRITICAL - 2024-05-26 12:22:19 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'cv'
[Method: CLI, Route: db:seed/CvSeeder]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\Database.php(68): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\Config.php(111): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
 3 SYSTEMPATH\Database\Seeder.php(98): CodeIgniter\Database\Config::forge(null)
 4 SYSTEMPATH\Commands\Database\Seed.php(71): CodeIgniter\Database\Seeder->__construct(Object(Config\Database))
 5 SYSTEMPATH\CLI\Commands.php(70): CodeIgniter\Commands\Database\Seed->run([...])
 6 SYSTEMPATH\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:seed', [...])
 7 SYSTEMPATH\Boot.php(338): CodeIgniter\CLI\Console->run()
 8 SYSTEMPATH\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
 9 ROOTPATH\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
ERROR - 2024-05-26 12:23:25 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'cv' in C:\xampp\htdocs\CV_CI4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\CV_CI4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'cv', 3306, '', 0)
#1 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(1471): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#4 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(1490): CodeIgniter\Database\BaseConnection->listTables()
#5 C:\xampp\htdocs\CV_CI4\system\Database\MigrationRunner.php(759): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#6 C:\xampp\htdocs\CV_CI4\system\Database\MigrationRunner.php(163): CodeIgniter\Database\MigrationRunner->ensureTable()
#7 C:\xampp\htdocs\CV_CI4\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\CV_CI4\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\CV_CI4\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\CV_CI4\system\Boot.php(338): CodeIgniter\CLI\Console->run()
#11 C:\xampp\htdocs\CV_CI4\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 C:\xampp\htdocs\CV_CI4\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'cv' in C:\xampp\htdocs\CV_CI4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(1471): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#3 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(1490): CodeIgniter\Database\BaseConnection->listTables()
#4 C:\xampp\htdocs\CV_CI4\system\Database\MigrationRunner.php(759): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#5 C:\xampp\htdocs\CV_CI4\system\Database\MigrationRunner.php(163): CodeIgniter\Database\MigrationRunner->ensureTable()
#6 C:\xampp\htdocs\CV_CI4\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#7 C:\xampp\htdocs\CV_CI4\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Migrate->run(Array)
#8 C:\xampp\htdocs\CV_CI4\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('migrate', Array)
#9 C:\xampp\htdocs\CV_CI4\system\Boot.php(338): CodeIgniter\CLI\Console->run()
#10 C:\xampp\htdocs\CV_CI4\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#11 C:\xampp\htdocs\CV_CI4\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#12 {main}
ERROR - 2024-05-26 12:24:10 --> mysqli_sql_exception: Table 'cv.cv' doesn't exist in C:\xampp\htdocs\CV_CI4\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp\htdocs\CV_CI4\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `cv...', 0)
#1 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cv...')
#2 C:\xampp\htdocs\CV_CI4\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cv...')
#3 C:\xampp\htdocs\CV_CI4\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cv...', Array, false)
#4 C:\xampp\htdocs\CV_CI4\app\Database\Seeds\CvSeeder.php(21): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\CV_CI4\system\Database\Seeder.php(147): App\Database\Seeds\CvSeeder->run()
#6 C:\xampp\htdocs\CV_CI4\system\Commands\Database\Seed.php(79): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#7 C:\xampp\htdocs\CV_CI4\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Seed->run(Array)
#8 C:\xampp\htdocs\CV_CI4\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:seed', Array)
#9 C:\xampp\htdocs\CV_CI4\system\Boot.php(338): CodeIgniter\CLI\Console->run()
#10 C:\xampp\htdocs\CV_CI4\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#11 C:\xampp\htdocs\CV_CI4\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-05-26 12:24:57 --> ErrorException: Undefined array key "name"
[Method: GET, Route: cv]
in APPPATH\Views\cv_view.php on line 36.
 1 APPPATH\Views\cv_view.php(36): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "name"', 'C:\\xampp\\htdocs\\CV_CI4\\app\\Views\\cv_view.php', 36)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\CV_CI4\\app\\Views\\cv_view.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('cv_view', [], true)
 5 APPPATH\Controllers\CvController.php(14): view('cv_view', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\CvController->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CvController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp\\htdocs\\CV_CI4\\public\\index.php')
CRITICAL - 2024-05-26 12:27:02 --> ErrorException: Undefined array key "name"
[Method: GET, Route: cv]
in APPPATH\Views\cv_view.php on line 36.
 1 APPPATH\Views\cv_view.php(36): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "name"', 'C:\\xampp\\htdocs\\CV_CI4\\app\\Views\\cv_view.php', 36)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\CV_CI4\\app\\Views\\cv_view.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('cv_view', [], true)
 5 APPPATH\Controllers\CvController.php(14): view('cv_view', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\CvController->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CvController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp\\htdocs\\CV_CI4\\public\\index.php')
CRITICAL - 2024-05-26 12:27:04 --> ErrorException: Undefined array key "name"
[Method: GET, Route: cv]
in APPPATH\Views\cv_view.php on line 36.
 1 APPPATH\Views\cv_view.php(36): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "name"', 'C:\\xampp\\htdocs\\CV_CI4\\app\\Views\\cv_view.php', 36)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\CV_CI4\\app\\Views\\cv_view.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('cv_view', [], true)
 5 APPPATH\Controllers\CvController.php(14): view('cv_view', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\CvController->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CvController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp\\htdocs\\CV_CI4\\public\\index.php')
CRITICAL - 2024-05-26 12:27:26 --> ErrorException: Undefined array key "name"
[Method: GET, Route: cv]
in APPPATH\Views\cv_view.php on line 36.
 1 APPPATH\Views\cv_view.php(36): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "name"', 'C:\\xampp\\htdocs\\CV_CI4\\app\\Views\\cv_view.php', 36)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\CV_CI4\\app\\Views\\cv_view.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('cv_view', [], true)
 5 APPPATH\Controllers\CvController.php(14): view('cv_view', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\CvController->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CvController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp\\htdocs\\CV_CI4\\public\\index.php')
CRITICAL - 2024-05-26 12:36:27 --> ErrorException: Undefined array key "name"
[Method: GET, Route: cv]
in APPPATH\Views\cv_view.php on line 36.
 1 APPPATH\Views\cv_view.php(36): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "name"', 'C:\\xampp\\htdocs\\CV_CI4\\app\\Views\\cv_view.php', 36)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\CV_CI4\\app\\Views\\cv_view.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('cv_view', [], true)
 5 APPPATH\Controllers\CvController.php(14): view('cv_view', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\CvController->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CvController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp\\htdocs\\CV_CI4\\public\\index.php')
